# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 05:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_auto_20151204_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='edition',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='listing',
            name='fifth_author_name',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='first_author_name',
            field=models.CharField(default=b'XXX', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='fourth_author_name',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='isbn',
            field=models.CharField(default=b'', max_length=13),
        ),
        migrations.AddField(
            model_name='listing',
            name='second_author_name',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='third_author_name',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.RemoveField(
            model_name='listing',
            name='book',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='current_bid',
        ),
        migrations.AlterUniqueTogether(
            name='listing',
            unique_together=set([('start_time', 'seller_email')]),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
