# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_remove_listing_current_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='first_author_name',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
