# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 04:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0031_auto_20151206_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('edition', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('first_author_name', models.CharField(max_length=200)),
                ('second_author_name', models.CharField(blank=True, default=b'', max_length=200)),
                ('third_author_name', models.CharField(blank=True, default=b'', max_length=200)),
                ('fourth_author_name', models.CharField(blank=True, default=b'', max_length=200)),
                ('fifth_author_name', models.CharField(blank=True, default=b'', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='fifth_author_name',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='first_author_name',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='fourth_author_name',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='second_author_name',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='third_author_name',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='title',
        ),
        migrations.AddField(
            model_name='listing',
            name='book_id',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
    ]
