# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0032_auto_20151207_0431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='book_id',
            new_name='book',
        ),
    ]
