# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0033_auto_20151207_0452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_time',
            field=models.IntegerField(verbose_name='bid time'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder_email',
            field=models.EmailField(max_length=254, verbose_name='auth.User'),
        ),
        migrations.AlterField(
            model_name='book',
            name='fifth_author_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='fourth_author_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='second_author_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='third_author_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='book',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('excellent', 'Excellent'), ('new', 'New')], default='good', max_length=9),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
